SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/ApiContacts__c.object-meta.xml
<CustomObject>
    <label>ApiContacts</label>
    <nameField>
        <label>ApiContacts Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <label>gender</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/classes/DaoApiContacts.cls
public with sharing class DaoApiContacts {


    /**
     * @description ApiContacts 객체의 ID에 해당하는 정보 SELECT
     */
    public static List<ApiContacts__c> fincById(ID apiContactsId) {

        List<ApiContacts__c> apiContactsList = [
            SELECT
                Id,
                Name,
                id__c,
                name__c,
                email__c,
                address__c,
                gender__c
                FROM ApiContacts__c
                WHERE Id = :apiContactsId
        ];

        return apiContactsList;
    }

    /**
     * @description ApiContacts 레코드 삭제
     */
    public static void deleteData(List<ApiContacts__c> apiContactsList) {
        try {
            delete apiContactsList;
        } catch(Exception e) {
            throw e;
        }
    }
}