SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/ApiContacts__c.object-meta.xml
<CustomObject>
    <label>ApiContacts</label>
    <nameField>
        <label>ApiContacts Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <label>gender</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/objects/ApiContacts__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SAMPLE_ACCOUNT_FOR_SALESFORCE/force-app/main/default/classes/ApiContactsClass.cls
public with sharing class ApiContactsClass {
    public ApiContactsClass() {}
    
    class TestContact {
        public List<ContactInfo> contacts {get; set;}
    }
    
    class ContactInfo {
        public String id;
        public String name; 
        public String email; 
        public String address;
        public String gender;
        // public PhoneInfo phone;
    }

    class PhoneInfo {
        public String mobile;
        public String home;
        public String office;
    }

    @AuraEnabled
    public static List<ApiContacts__c> insertData() {    
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://api.androidhive.info/contacts/');
        req.setMethod('GET');               
        
        try {            
            Http http = new Http();
            HTTPResponse res = http.send(req);            
            ApiContactsClass.TestContact testContacts = (ApiContactsClass.TestContact)JSON.deserialize(res.getBody(), ApiContactsClass.TestContact.class);
            
            List<ApiContacts__c> ac = new List<ApiContacts__c>();

            for(integer i = 0; i< 12; i++) {
                
                ApiContacts__c acc = new ApiContacts__c();

                acc.id__c = testContacts.contacts[i].id;
                acc.name__c = testContacts.contacts[i].name;
                acc.email__c = testContacts.contacts[i].email;
                acc.address__c = testContacts.contacts[i].address;
                acc.gender__c = testContacts.contacts[i].gender;
                
                ac.add(acc);
               
            }
             insert ac;
            
             return ac;
            
        } catch (System.Exception e) {          
            // this.id = e.getMessage();    
            return null;
        }            
    }
    
      @AuraEnabled
      public static List<ApiContacts__c> deleteData() {
        List<ApiContacts__c> ac = [SELECT id__c, name__c, email__c, address__c, gender__c FROM ApiContacts__c];
        delete ac;
        return ac;
    }
}